#theme
# theme: jekyll-theme-tactile

# Site Settings
title: M. Batelaan blog
description: This is my blog site
subtitle: 
name: M Batelaan
url: "https://mbatelaan.github.io/mbatelaan"
repository: "https://github.com/mbatelaan"
github_username:  mbatelaan

lsi: false
safe: true
source: mbatelaan
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
