#theme
# theme: jekyll-theme-tactile

# Site Settings
title: M. Batelaan blog
description: This is my blog site
subtitle: PhD research
name: Mischa Batelaan
url: "https://pages.github.cs.adelaide.edu.au/a1688714/a1688714"
repository: "https://github.cs.adelaide.edu.au/a1688714/a1688714"
github_username:  a1688714

lsi: false
safe: true
source: a1688714
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
