#theme
remote_theme: "mmistakes/minimal-mistakes@4.16.5"
minimal_mistakes_skin: "dark"

# Site Settings
title: M. Batelaan blog
description: This is my blog site
subtitle: PhD research
name: Mischa Batelaan
url: "https://pages.github.cs.adelaide.edu.au/a1688714/a1688714"
repository: "https://github.cs.adelaide.edu.au/a1688714/a1688714"
